function [EEG, Trial] = func_read_csv_logfile(cfg, EEG, subject_name)


%% read csv file
this_logfile = local_importfile([cfg.dir.behavior, subject_name, '.csv']);
first_blocktrials_idxs = 1:144:1008;


this_logfile.prev_resp = [nan; this_logfile.bin_resp(1:end-1)];
this_logfile.prev_resp(first_blocktrials_idxs) = nan; 

this_logfile.prev_signal = [nan; this_logfile.signal(1:end-1)];
this_logfile.prev_signal(first_blocktrials_idxs) = nan;

this_logfile.prev_feedback = ['None'; this_logfile.SDT_type(1:end-1)];
this_logfile.prev_feedback(first_blocktrials_idxs) = 'None';

Trial = table2struct(this_logfile);
EEG.trialinfo = Trial;


end


function EX = local_importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EX = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  EX = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  EX = importfile("/data5/Elio/alphaNoise/Preprocessing/rawdata/Logfiles/01EX.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Aug-2021 14:15:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "cue_type", "cue_valence", "signal", "color_cue", "cnt_probed", "energy_probed", "phase_angle_probed", "bin_resp", "confidence", "RT", "feed_type", "score_detection", "score_confidence", "score_trl", "cumulative_score", "cumulative_EUR", "jitter", "accurate_detection", "SDT_type", "Presp_aimed", "alpha_est", "gamma_est"];
opts.VariableTypes = ["double", "categorical", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["cue_type", "cue_valence", "color_cue", "feed_type", "SDT_type"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "energy_probed", "TrimNonNumeric", true);
opts = setvaropts(opts, "energy_probed", "ThousandsSeparator", ",");

% Import the data
EX = readtable(filename, opts);

end


